[package]
name = "fieldcad-electromagnetism"
version = "0.1.0"
edition = "2024"

[dependencies]
fieldcad-core = { workspace = true }
fieldcad-electromagnetic-sources = { workspace = true }
fieldcad-sources = { workspace = true }
fieldcad-particles = { workspace = true }
fieldcad-plugin-api = { workspace = true }
glam = { workspace = true }

[dev-dependencies]
fieldcad-electrostatics = { workspace = true }
