[package]
name = "fieldcad-simulation"
version = "0.1.0"
edition = "2024"

[dependencies]
fieldcad-core = { workspace = true }
fieldcad-plugin-api = { workspace = true }
glam = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
fieldcad-electromagnetism = { workspace = true }
fieldcad-electrostatics = { workspace = true }
fieldcad-test-field = { workspace = true }
